name: crypto_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.12.12
  - cuda-cccl_win-64=12.8.90
  - cuda-cudart-dev_win-64=12.8.90
  - cuda-cudart-static_win-64=12.8.90
  - cuda-cudart_win-64=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-version=12.8
  - cupy=13.6.0
  - cupy-core=13.6.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fastapi=0.127.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.127.0
  - fastrlock=0.8.3
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libabseil=20250512.1
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcrc32c=1.1.2
  - libcublas=12.8.4.1
  - libcufft=11.3.3.83
  - libcurand=10.3.9.90
  - libcurl=8.18.0
  - libcusolver=11.7.3.90
  - libcusparse=12.5.8.93
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - liblzma=5.8.1
  - libnvjitlink=12.8.93
  - libparquet=23.0.0
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - narwhals=2.7.0
  - nest-asyncio=1.6.0
  - numba=0.62.1
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openpyxl=3.1.5
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pip=25.3
  - platformdirs=4.5.0
  - plotly=6.3.0
  - polars=1.35.2
  - polars-runtime-32=1.35.2
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - pure_eval=0.2.3
  - pyarrow-core=23.0.0
  - pycparser=2.23
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.10.6
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyparsing=3.3.2
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-gil=3.12.12
  - python-multipart=0.0.21
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2025.11.05
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - scipy=1.16.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlalchemy=2.0.44
  - stack_data=0.6.3
  - starlette=0.50.0
  - statsmodels=0.14.5
  - svgwrite=1.4.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tomli=2.3.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typer=0.20.1
  - typer-slim=0.20.1
  - typer-slim-standard=0.20.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchfiles=1.1.1
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - backtesting==0.6.5
      - bokeh==3.8.1
      - bottle==0.13.4
      - clr-loader==0.2.9
      - contourpy==1.3.3
      - lightweight-charts==2.1
      - pillow==12.0.0
      - proxy-tools==0.1.0
      - pyarrow==23.0.0
      - pybit==5.13.0
      - pycryptodome==3.23.0
      - pysocks==1.7.1
      - pyswisseph==2.10.3.2
      - pythonnet==3.0.5
      - pywebview==6.1
      - tqdm==4.67.1
      - websocket-client==1.9.0
      - xyzservices==2025.11.0
